[project]
name = "jira"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

# uv pip compile pyproject.toml -o ./requirements.txt
dependencies = [
    "dify-plugin>=0.6.0",
    "atlassian-python-api>=4.0.3",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
