[project]
name = "tavily"
version = "0.1.3"
description = "A powerful AI-native search engine and web content extraction tool for Dify"
readme = "README.md"
requires-python = ">=3.12"

# uv pip compile pyproject.toml -o ./requirements.txt
dependencies = [
    "dify_plugin>=0.3.0,<0.5.0",
    "tavily-python==0.7.19",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
