[project]
name = "volcengine_ark"
version = "0.0.1"
description = "Volcengine Ark base-model invocation"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "dify_plugin==0.7.0",
  "volcengine-python-sdk[ark]>=5.0.1,<6.0.0",
]

[dependency-groups]
dev = ["pytest"]
