[project]
name = "volcengine_maas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

# uv pip compile pyproject.toml -o ./requirements.txt
dependencies = [
    "dify_plugin<0.6.0,>=0.5.0",
    "volcengine-python-sdk==4.0.39",
    "pytz==2024.2",
    "websockets==15.0.1",
    "websocket-client==1.8.0",
    "sniffio~=1.3.1",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
