[project]
name = "dify-plivo-sms"
version = "0.1.0"
description = "Plivo SMS tool plugin for Dify"
readme = "README.md"
requires-python = ">=3.12"

# uv pip compile pyproject.toml -o ./requirements.txt
dependencies = [
    "dify_plugin==0.7.1",
    "plivo==4.59.5",
]

[dependency-groups]
dev = []
