[project]
name = "transcript"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

# uv pip compile pyproject.toml -o ./requirements.txt
dependencies = [
    "dify_plugin==0.0.1b65",
    "youtube_transcript_api~=0.6.3",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
