[project]
name = "monday"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

# uv pip compile pyproject.toml -o ./requirements.txt
dependencies = [
    "monday-api-python-sdk @ git+https://github.com/jingfelix/monday-api-python-sdk.git@v1.3.1.post1",
    "dify-easy>=0.1.0",
    "dify_plugin>=0.3.0,<0.5.0",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
