[project]
name = "dicom_reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

# uv pip compile pyproject.toml -o ./requirements.txt
dependencies = [
    "dify_plugin>=0.4.0,<0.7.0",
    "pydicom>=2.4.4,<3.0.0",
    "numpy>=1.26,<2.0",
    "Pillow>=10.0,<11.0",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
