[project]
name = "dify-qrcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

# uv pip compile pyproject.toml -o ./requirements.txt
dependencies = [
    "dify_plugin>=0.3.1,<=0.4.0",
    "qrcode~=8.2",
    "pypng==0.20220715.0",
    "pillow~=12.1.1",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
